name: cron-workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron-job:
    name: cron-job-name
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: echo
        run: echo job triggered
