name: MyWorkflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.4'
      - name: test
        run: make test
