name: MyWorkflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: ls
        run: ls -la
      - name: env
        run: go version
      - name: test
        run: make test
