name: test
on:
  push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.13.4'
          - '1.14.2'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make test
